"""initial schema

Revision ID: bdc747c7de4d
Revises: 
Create Date: 2026-09-03 19:45:37.956505
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'bdc747c7de4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('updated_by_email', sa.String(length=320), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('business_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('capability_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('magic_link_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('redirect_path', sa.String(length=500), nullable=False),
    sa.Column('remember_me', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('magic_link_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magic_link_tokens_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_magic_link_tokens_expires_at'), ['expires_at'], unique=False)

    op.create_table('publish_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rate_limit_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=320), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_limit_counters', schema=None) as batch_op:
        batch_op.create_index('ix_rate_limit_bucket', ['scope', 'key', 'window_start'], unique=False)

    op.create_table('reference_sequences',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sign_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_domain'), ['domain'], unique=False)

    op.create_table('capabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['capability_areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_no', sa.String(length=20), nullable=True),
    sa.Column('offering_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('business_group_id', sa.Integer(), nullable=True),
    sa.Column('cto_aware', sa.Boolean(), nullable=True),
    sa.Column('customer_challenge', sa.Text(), nullable=False),
    sa.Column('technical_description', sa.Text(), nullable=False),
    sa.Column('key_benefits', sa.Text(), nullable=False),
    sa.Column('readiness_level', sa.String(length=40), nullable=True),
    sa.Column('readiness_programs', sa.Text(), nullable=False),
    sa.Column('deployment_status', sa.String(length=20), nullable=True),
    sa.Column('deployment_detail', sa.Text(), nullable=False),
    sa.Column('additional_customers', sa.Text(), nullable=False),
    sa.Column('current_pipeline', sa.Text(), nullable=False),
    sa.Column('resource_links_notes', sa.Text(), nullable=False),
    sa.Column('created_by_email', sa.String(length=320), nullable=False),
    sa.Column('assigned_reviewer_email', sa.String(length=320), nullable=True),
    sa.Column('approved_version_id', sa.Integer(), nullable=True),
    sa.Column('publish_destination_id', sa.Integer(), nullable=True),
    sa.Column('published_url', sa.String(length=1000), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_action_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_group_id'], ['business_groups.id'], ),
    sa.ForeignKeyConstraint(['publish_destination_id'], ['publish_destinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_no')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_business_group_id'), ['business_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_created_by_email'), ['created_by_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_status'), ['status'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('business_group_id', sa.Integer(), nullable=True),
    sa.Column('granted_by_email', sa.String(length=320), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_email', sa.String(length=320), nullable=True),
    sa.ForeignKeyConstraint(['business_group_id'], ['business_groups.id'], ),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_email'), ['email'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('blob_path', sa.String(length=600), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_email', sa.String(length=320), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_submission_id'), ['submission_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('author_email', sa.String(length=320), nullable=False),
    sa.Column('author_name', sa.String(length=150), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_submission_id'), ['submission_id'], unique=False)

    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('template', sa.String(length=60), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_log_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_log_submission_id'), ['submission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_log_to_email'), ['to_email'], unique=False)

    op.create_table('page_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('viewer_email', sa.String(length=320), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_views_submission_id'), ['submission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_views_viewed_at'), ['viewed_at'], unique=False)

    op.create_table('review_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by_email', sa.String(length=320), nullable=True),
    sa.Column('closed_reason', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_cycles_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cycles_submission_id'), ['submission_id'], unique=False)

    op.create_table('submission_capabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('other_text', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'capability_id')
    )
    with op.batch_alter_table('submission_capabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_capabilities_submission_id'), ['submission_id'], unique=False)

    op.create_table('submission_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('contact_role', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_contacts_submission_id'), ['submission_id'], unique=False)

    op.create_table('workflow_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=False),
    sa.Column('actor_name', sa.String(length=150), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_events_actor_email'), ['actor_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_submission_id'), ['submission_id'], unique=False)

    op.create_table('submission_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('approval_event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_event_id'], ['workflow_events.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_versions_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_versions_submission_id'))

    op.drop_table('submission_versions')
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_events_submission_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_actor_email'))

    op.drop_table('workflow_events')
    with op.batch_alter_table('submission_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_contacts_submission_id'))
        batch_op.drop_index(batch_op.f('ix_submission_contacts_email'))

    op.drop_table('submission_contacts')
    with op.batch_alter_table('submission_capabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_capabilities_submission_id'))

    op.drop_table('submission_capabilities')
    with op.batch_alter_table('review_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_cycles_submission_id'))
        batch_op.drop_index(batch_op.f('ix_review_cycles_due_at'))

    op.drop_table('review_cycles')
    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_views_viewed_at'))
        batch_op.drop_index(batch_op.f('ix_page_views_submission_id'))

    op.drop_table('page_views')
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_log_to_email'))
        batch_op.drop_index(batch_op.f('ix_notification_log_submission_id'))
        batch_op.drop_index(batch_op.f('ix_notification_log_status'))

    op.drop_table('notification_log')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_submission_id'))

    op.drop_table('comments')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_submission_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_email'))

    op.drop_table('user_roles')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_submissions_created_by_email'))
        batch_op.drop_index(batch_op.f('ix_submissions_business_group_id'))

    op.drop_table('submissions')
    op.drop_table('capabilities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_domain'))

    op.drop_table('users')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_sessions_email'))

    op.drop_table('sessions')
    op.drop_table('reference_sequences')
    with op.batch_alter_table('rate_limit_counters', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_limit_bucket')

    op.drop_table('rate_limit_counters')
    op.drop_table('publish_destinations')
    with op.batch_alter_table('magic_link_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magic_link_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('ix_magic_link_tokens_email'))

    op.drop_table('magic_link_tokens')
    op.drop_table('capability_areas')
    op.drop_table('business_groups')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
